---
- hosts: all
  tasks: 
  - name: install packages essential for packages
    become: yes
    apt: 
        pkg:
        - python-apt
        - python-pycurl
        state: latest 
        update_cache: yes
  - name: install packages essential for ansible+vagrant stuff
    become: yes
    apt: 
        pkg: 
        - mtr-tiny
        - mysql-common
        - mysql-server
        - net-tools
        - netbase
        - netcat-traditional
        - nfs-common
        - nginx-common
        - nginx-extras
        - openssh-client
        - openssh-server
        - php-pear
        - php7.4
        - php7.4-cgi
        - php7.4-cli
        - php7.4-common
        - php7.4-curl
        - php7.4-fpm
        - php7.4-gd
        - php7.4-mysqlnd
        - procmail
        - unzip
        - util-linux
        - vim
        - vim-common
        - vim-runtime
        - wget
        - python3-mysqldb
        state: latest 
        update_cache: yes

  - name: Copy nginx configuration for wordpress
    template: src=nginx/defconfig dest=/etc/nginx/sites-available/default
    become: yes
  - name: Copy PHP Configuration
    template: src=php/php.ini dest=/etc/php/7.4/fpm/php.ini
    become: yes
  - name: restart php
    become: yes
    service: name=php7.4-fpm state=restarted
  - name: restart nginx
    become: yes
    service: name=nginx state=restarted
  - mysql_db: name=wp state=present
    become: yes
  - name: Create database user with name 'bob' and password '12345' with all database privileges
    community.mysql.mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
    become: yes
  - name: Install WP-CLI
    become: yes
    get_url: url="https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar" dest="/usr/bin/wp" mode=0755
  - name: Download wordpress into /webroot using wp[-cli]
    command: wp core download --path=/webroot/
    ignore_errors: True
  - name: Configure Wordpress
    command: wp core config --path=/webroot/ --dbname="wp" --dbuser="bob" --dbpass="12345"  --dbprefix="local_"
    ignore_errors: True
  - debug:
      msg: "{{ansible_all_ipv4_addresses | difference([ansible_default_ipv4.address]) | first }}"
  - name: Install wordpress
    command: wp core install --path=/webroot/ --url=http://{{ansible_all_ipv4_addresses | difference([ansible_default_ipv4.address]) | first }}/ --title="DevBox" --admin_user=admin --admin_password=password --admin_email=admin@localhost.com
    ignore_errors: True
  - name: Create Editor
    command: wp --path=/webroot/ user create editor editor@localhost.com --role=editor --user_pass=password
    ignore_errors: True
  - name: Create Author
    command: wp --path=/webroot/ user create author author@localhost.com --role=author --user_pass=password
    ignore_errors: True
  - name: Create subscriber
    command: wp --path=/webroot/ user create subscriber subscriber@localhost.com --role=subscriber --user_pass=password
    ignore_errors: True
  - name: Create Contributor
    command: wp --path=/webroot/ user create contributor contributor@localhost.com --role=contributor --user_pass=password
    ignore_errors: True
